apiVersion: apps/v1
kind: Deployment
metadata:
  name: astralis-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astralis-backend
  template:
    metadata:
      labels:
        app: astralis-backend
    spec:
      containers:
        - name: backend
          image: astralis-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: astralis-secrets
                  key: database-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: astralis-secrets
                  key: secret-key
            - name: ENV
              value: "development"
            - name: FRONTEND_URL
              value: "http://localhost:8080"
            - name: ML_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: astralis-config
                  key: ml-service-url

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8000
  selector:
    app: astralis-backend
