apiVersion: v1
kind: Secret
metadata:
  name: astralis-secrets
type: Opaque
stringData:
  postgres-user: "user"
  postgres-password: "password"
  postgres-db: "astralis"
  database-url: "postgresql://user:password@astralis-db:5432/astralis"
  secret-key: "dev_secret_cambia_en_produccion"
